server:
  port: 80

spring:
  mvc:
    view:
      suffix: .html
      prefix: /
    pathmatch:
      #解决io.springfox的swagger接口文档的冲突
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 2048MB
      file-size-threshold: 4096MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.5.34/trahrs?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: a13850526746

# mybatis-plus配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:mapper/*Mapper.xml
  #type-aliases-package: cn.etcom.entity
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ASSIGN_ID
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

